FROM node:16-alpine

RUN apk add bash
RUN apk add git

RUN mkdir /game_rps
RUN mkdir /game_rps/client
WORKDIR /game_rps/client


ADD client/package.json ./
RUN npm update
RUN npm install

ADD game_engine /game_rps/game_engine
ADD client/src ./src
ADD client/webpack ./webpack
ADD client/index.html ./
ADD client/.babelrc ./

CMD npm run start